### ISSUE TITLE
hi why not npm install ?

### ISSUE THREAD

**Issue by ddpdev** [tranquangvu/react-native-uploader#2]
first, thanks your module ^^;

when npm installed , error occured.

==> npm install https://github.com/tranquangvu/react-native-uploader.git --save

ERR! not fount:git

...
 error git clone --template=C:\Users\leesy\AppData\Roaming\npm-cache_git-remotes_templates --mirror https://github.com/tranquangvu/react-native-uploader.git C:\Users\leesy\AppData\Roaming\npm-cache_git-remotes\git-https-github-com-tranquangvu-react-native-uploader-git-4298aac2: undefined
23 error git clone --template=C:\Users\leesy\AppData\Roaming\npm-cache_git-remotes_templates --mirror https://github.com/tranquangvu/react-native-uploader.git C:\Users\leesy\AppData\Roaming\npm-cache_git-remotes\git-https-github-com-tranquangvu-react-native-uploader-git-4298aac2: undefined
24 silly fetchPackageMetaData Error: not found: git
24 silly fetchPackageMetaData     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:63:19)
24 silly fetchPackageMetaData     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:72:29)
24 silly fetchPackageMetaData     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:81:16
24 silly fetchPackageMetaData     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
24 silly fetchPackageMetaData     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
24 silly fetchPackageMetaData     at FSReqWrap.oncomplete (fs.js:117:15)
24 silly fetchPackageMetaData  error for https://github.com/tranquangvu/react-native-uploader.git { Error: not found: git
24 silly fetchPackageMetaData     at F (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:63:19)
24 silly fetchPackageMetaData     at E (C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:72:29)
24 silly fetchPackageMetaData     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\which.js:81:16
24 silly fetchPackageMetaData     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\index.js:44:5
24 silly fetchPackageMetaData     at C:\Program Files\nodejs\node_modules\npm\node_modules\which\node_modules\isexe\windows.js:29:5
24 silly fetchPackageMetaData     at FSReqWrap.oncomplete (fs.js:117:15) code: 'ENOGIT' }
25 silly rollbackFailedOptional Starting
26 silly rollbackFailedOptional Finishing
... 

could you help me ?

(ps. but, git clone well done ^^;)

**Comment by ddpdev** [comment]
maybe firewall ...  network change then success... thanks
